// <auto-generated />
using System;
using DoAnWeb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnWeb.Migrations
{
    [DbContext(typeof(Applicationcs))]
    [Migration("20240331153523_Wed")]
    partial class Wed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnWeb.Models.CTDonHang", b =>
                {
                    b.Property<int>("IdCTDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCTDH"));

                    b.Property<int>("IdDH")
                        .HasColumnType("int");

                    b.Property<int>("IdSP")
                        .HasColumnType("int");

                    b.HasKey("IdCTDH");

                    b.HasIndex("IdDH");

                    b.HasIndex("IdSP");

                    b.ToTable("CTDonHangs");
                });

            modelBuilder.Entity("DoAnWeb.Models.DanhGia", b =>
                {
                    b.Property<int>("IdDG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDG"));

                    b.Property<string>("BinhLuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdSP")
                        .HasColumnType("int");

                    b.HasKey("IdDG");

                    b.HasIndex("Id");

                    b.HasIndex("IdSP");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("DoAnWeb.Models.DonHang", b =>
                {
                    b.Property<int>("IdDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDH"));

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("TGGiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TGLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThanhTien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TongTien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiDon")
                        .HasColumnType("bit");

                    b.HasKey("IdDH");

                    b.HasIndex("Id");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("DoAnWeb.Models.KhuyenMai", b =>
                {
                    b.Property<string>("IdKM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhanTramGiam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TGBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TGKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdKM");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("DoAnWeb.Models.LoaiSP", b =>
                {
                    b.Property<int>("IdLoaiSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoaiSP"));

                    b.Property<string>("TenLoaiSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdLoaiSP");

                    b.ToTable("LoaiSPs");
                });

            modelBuilder.Entity("DoAnWeb.Models.LoaiTaiKhoan", b =>
                {
                    b.Property<int>("IdLoaiTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoaiTK"));

                    b.Property<string>("LoaiTK")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdLoaiTK");

                    b.ToTable("LoaiTaiKhoans");
                });

            modelBuilder.Entity("DoAnWeb.Models.SanPham", b =>
                {
                    b.Property<int>("IdSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSP"));

                    b.Property<string>("Gia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhLon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhNho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdKM")
                        .HasColumnType("int");

                    b.Property<int>("IdLoaiSP")
                        .HasColumnType("int");

                    b.Property<string>("KhuyenMaiIdKM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soluong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSP");

                    b.HasIndex("IdLoaiSP");

                    b.HasIndex("KhuyenMaiIdKM");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("DoAnWeb.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdLoaiTK")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenDN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdLoaiTK");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("DoAnWeb.Models.CTDonHang", b =>
                {
                    b.HasOne("DoAnWeb.Models.DonHang", "DonHangs")
                        .WithMany("CTDonHangs")
                        .HasForeignKey("IdDH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnWeb.Models.SanPham", "SanPham")
                        .WithMany("CTDonHangs")
                        .HasForeignKey("IdSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHangs");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DoAnWeb.Models.DanhGia", b =>
                {
                    b.HasOne("DoAnWeb.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("DanhGias")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnWeb.Models.SanPham", "SanPham")
                        .WithMany("DanhGias")
                        .HasForeignKey("IdSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAnWeb.Models.DonHang", b =>
                {
                    b.HasOne("DoAnWeb.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("DonHangs")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAnWeb.Models.SanPham", b =>
                {
                    b.HasOne("DoAnWeb.Models.LoaiSP", "LoaiSP")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdLoaiSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnWeb.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("SanPhams")
                        .HasForeignKey("KhuyenMaiIdKM");

                    b.Navigation("KhuyenMai");

                    b.Navigation("LoaiSP");
                });

            modelBuilder.Entity("DoAnWeb.Models.TaiKhoan", b =>
                {
                    b.HasOne("DoAnWeb.Models.LoaiTaiKhoan", "LoaiTaiKhoan")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("IdLoaiTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiTaiKhoan");
                });

            modelBuilder.Entity("DoAnWeb.Models.DonHang", b =>
                {
                    b.Navigation("CTDonHangs");
                });

            modelBuilder.Entity("DoAnWeb.Models.KhuyenMai", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DoAnWeb.Models.LoaiSP", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DoAnWeb.Models.LoaiTaiKhoan", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("DoAnWeb.Models.SanPham", b =>
                {
                    b.Navigation("CTDonHangs");

                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("DoAnWeb.Models.TaiKhoan", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
